name: Update Stocks CSV

on:
  schedule:
    - cron: "0 6 * * *"   # every day at 6 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install requests

      - run: python scripts/update_csv.py

      - run: |
          git config --global user.name "ghoshraja9860"
          git config --global user.email "ghoshraja9860@gmail.com"
          git add stocks.csv
          git commit -m "Auto-update stocks.csv" || echo "No changes"
          git push
